### ISSUE TITLE
codec error with analyze_convergence.py

### ISSUE THREAD

**Issue by frozenmess** [zhonge/cryodrgn#217] opened 2023-02-01 01:57 UTC
Hello everyone,

I am having an error running analyze_convergence.py with my version 1.0.0 install. cryoDRGN programs have run fine for everything else thus far (downsampling, training, and analyze jobs) and I had previously (months ago) run analyze_convergence.py with no issue. Today I installed cryoDRGN2 on a different workstation and am getting the same error message.

Here is the error I am receiving: 

2023-01-31 19:25:20,253 Namespace(workdir='/data/apm4/HSP165/758-c1concensus/01_128_8D_256', epoch=99, outdir=None, epoch_interval=5, force_umap_cpu=False, subset=50000, random_seed=None, random_state=42, n_epochs_umap=25000, skip_umap=False, n_bins=30, smooth=True, smooth_width=1.0, pruned_maxima=12, radius=5.0, final_maxima=10, Apix=1.0, flip=False, invert=False, downsample=None, device=None, skip_volgen=False, max_threads=8, thresh=None, dilate=3, dist=10) (analyze_convergence.py:1076)
2023-01-31 19:25:20,281 Saving all results to /data/apm4/HSP165/758-c1concensus/01_128_8D_256/convergence.99 (analyze_convergence.py:1088)
2023-01-31 19:25:20,369 Convergence 1: plotting total loss curve ... (analyze_convergence.py:1117)
Traceback (most recent call last):
  File "/data/apm4/cryodrgn-dir/cryodrgn/utils/analyze_convergence.py", line 1241, in <module>
    main(parser.parse_args())
  File "/data/apm4/cryodrgn-dir/cryodrgn/utils/analyze_convergence.py", line 1118, in main
    plot_loss(logfile, outdir, E)
  File "/data/apm4/cryodrgn-dir/cryodrgn/utils/analyze_convergence.py", line 199, in plot_loss
    loss = analysis.parse_loss(logfile)
  File "/home/apm4/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/analysis.py", line 22, in parse_loss
    lines = open(f).readlines()
  File "/home/apm4/miniconda3/envs/cryodrgn/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 918: invalid start byte

---

So it seems there is something unicode-8 can't decode (maybe and Å or some other symbol). I've tried editing the open function's mode to 'rb' in crydrgn's codec.py, but the error persists. Does anyone have any suggestions on alleviating this? 

Thank you.

**Comment by vineetbansal** [comment] 2023-02-01 15:23
@frozenmess - thanks for opening the issue. We did make a change to the logging mechanism which was merged yesterday, which may or may not be the cause of the issue here. Would you mind sending us the `run.log` file (which should have been generated in the same folder where you ran the cryoDRGN workflow since I see above that `outdir` is `None`). I suspect we may have to tweak this function (and any other function that deals with parsing the log files).

**Comment by frozenmess** [comment] 2023-02-01 16:13
Thank you for the reply.

There was no run.log in the working directory I ran the script from. It does generate a convergence.99 directory with a convergence.log file in the training results folder 01_128_8D_256/. The only run.log I see if from the training job.

---

Namespace(workdir='/data/apm4/HSP165/758-c1concensus/01_128_8D_256', epoch=99, outdir=None, epoch_interval=5, force_umap_cpu=False, subset=50000, random_seed=None, random_state=42, n_epochs_umap=25000, skip_umap=False, n_bins=30, smooth=True, smooth_width=1.0, pruned_maxima=12, radius=5.0, final_maxima=10, Apix=1.0, flip=False, invert=False, downsample=None, device=None, skip_volgen=False, max_threads=8, thresh=None, dilate=3, dist=10)
Saving all results to /data/apm4/HSP165/758-c1concensus/01_128_8D_256/convergence.99
Convergence 1: plotting total loss curve ...

---

If I designate an output directory with --outdir I get the same unicode error.

**Comment by zhonge** [comment] 2023-02-01 20:53
Thanks for reporting. It looks like the recent switch in our logging might have broken `analysis.parse_loss`. We'll take a look. (Note this may also break the plotting of the loss curve in the cryoDRGN jupyter notebooks)

**Comment by vineetbansal** [comment] 2023-02-01 21:44
@frozenmess - sorry, I misspoke. Going by the above output, you should see a `run.log` file in the folder `/data/apm4/HSP165/758-c1concensus/01_128_8D_256`. This is the one that `parse_loss` is trying to parse.

I'm unable to reproduce the error on my end (`analyze_convergence.py` when run against a newly generated output folder from `cryodrgn train_vae` after we made the logging tweaks works just fine) so this file will help immensely if you can find it and send over.

**Comment by frozenmess** [comment] 2023-02-02 01:57
[run.log](https://github.com/zhonge/cryodrgn/files/10564092/run.log)

Got it. Let me know if there are any issues with the file.

**Comment by frozenmess** [comment] 2023-02-02 18:10
I removed the junk characters in the run.log file and analyze_convergence.py worked fine. I'm not certain, but it does seem that the junk characters came in around the time I tried to continue my training with more epochs. I believe there were some issues in my submission script when I tried doing that, so maybe that is when those characters were put in.

Thank you very much for the help on this!

**Comment by vineetbansal** [comment] 2023-02-03 14:13
Glad you got it fixed for now. I'll close this issue but feel free to reopen if the problem resurfaces.

**Closed by vineetbansal** 2023-02-03 14:13 UTC
