### ISSUE TITLE
abinit_het using old pose format

### ISSUE THREAD

**Issue by mbelouso** [zhonge/cryodrgn#185] opened 2022-11-17 22:13 UTC
The bug is in how abinit_het and abinit_homo write out the pose.pkl. 

I run the command:

`cryodrgn abinit_het 128box.txt --ctf ctf.pkl --ind ind80k.pkl --zdim 6 -o drgn2_het --max-threads 8 --multigpu -b 4`

It runs perfectly, but when I try to run:

`cryodrgn backproject_voxel 128box.txt --poses drgn2_het/pose.pkl --ctf ctf.pkl --ind ind80k.pkl -o Initialvols.mrc`

or:

`cryodrgn analyze drgn2_het/ 29`

I get the following error:

> AssertionError: ERROR: Old pose format detected. Translations must be in units of fraction of box.

It appears that the abinit subroutine is writing out the older format for pose.pkl

**Comment by vineetbansal** [comment] 2022-11-17 23:40
Thanks for opening the issue @mbelouso - we should be able to fix this fairly quickly.

**Comment by vineetbansal** [comment] 2022-11-18 15:31
@zhonge - getting your thoughts here:

I ran through the scenario (abinit_het + backprojection), and can reproduce the error.

It seems to me that we shouldn't be messing (scaling translations by `D`) with the `poses.pkl` that is saved when checkpointing the model, or when saving the final `poses.pkl` (since I assume it can be picked up again by the user as the starting point when restarting the process..), since that is inherently tied to the the model. But is there any harm in scaling by `D` (if needed) silently when reading the translations, instead of the complaining about it? for example, changing what is currently:

```
assert np.all(trans <= 1), "ERROR: Old pose format detected. Translations must be in units of fraction of box."
trans *= D
```

to:

```
if np.all(trans <= 1):  # if the new pose format (translations in box fraction) is detected
    trans *= D
```

`pose.py` and `translate_mrcs.py` are the two places where this would need to be done.

**Comment by zhonge** [comment] 2022-11-18 15:37
We should save/load all translations in fractions not in pixel units. The pixel units is an outdated format from an earlier version of cryoDRGN2. I think we would need to convert the poses with D before saving in `abinit_homo` and `abinit_het`.

**Comment by vineetbansal** [comment] 2022-11-18 15:52
Ok - we could saved the fractional translations. But since the model is running in pixel translation units, if loading from a checkpoint, we'd have to scale up by `D`, like here:

https://github.com/zhonge/cryodrgn/blob/149b035f373021c4b8e6c699e51756bd1ab93fff/cryodrgn/commands/abinit_het.py#L842

And since we don't know whether the checkpoint was saved before or after we made this tweak, we'd have to make this conditional on the detected values of the poses.

Does that sound right?

**Comment by zhonge** [comment] 2022-11-18 15:54
We should enforce that all poses are saved in fractional units and not support this older version (that was never officially released).

**Comment by vineetbansal** [comment] 2022-11-28 16:19
@mbelouso - these fixes have now been merged to `master`. `abinit_het` and `abinit_homo` should now write out the pose `.pkl` in a format that `backproject_voxel` can work with. Can you give this a spin? I'll close the issue once you confirm this is resolved.

**Comment by mbelouso** [comment] 2022-11-28 23:55
Hey, So i pulled the latest master and ran the following command:

`cryodrgn abinit_het 64box.txt --ctf ctf.pkl --ind ind80k.pkl --zdim 6 -o het6_new --max-threads 8 --multigpu -b 4 -n 10`

This is on the same dataset which worked with the last version of cryodrgn. Now I get the following error after it completes the first epoch.


_Traceback (most recent call last):
  File "/home/cryosparc/anaconda3/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/abinit_het.py", line 1053, in main
    save_checkpoint(
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/abinit_het.py", line 602, in save_checkpoint
    trans /= model.lattice.D
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'lattice'_

**Comment by vineetbansal** [comment] 2022-11-29 00:23
@mbelouso - ah, I see the problem. Sorry about that - we haven't been able to test the code exhaustively in the multi-gpu case. I'll add a fix for this soon. In the meantime, can you omit the `--multigpu` argument (unless it makes your use case too slow). Fix coming soon..

**Comment by mbelouso** [comment] 2022-11-29 21:38
Yep, works perfectly (except for the multigpu option). 

Both `cryodrgn analyze` and `cryodrgn backproject_voxel` give expected results.

**Comment by vineetbansal** [comment] 2022-12-08 17:20
Thanks @mbelouso - since this particular concern is fixed, I'm closing this issue. Feel free to reopen in case we've overlooked anything.

**Closed by vineetbansal** 2022-12-08 17:20 UTC
